# GET request for the home page
GET / HTTP/1.1
Host: localhost:8080

###

# GET request for a specific file in the 'frontend' directory
GET /frontend HTTP/1.1
Host: localhost:8080

###

# GET request for /jotham
GET /jotham HTTP/1.1
Host: localhost:8080

###

# GET request for /jathniel
GET /jathniel HTTP/1.1
Host: localhost:8080

###
